### ISSUE TITLE
CD isn't working

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/frontend#431]
Need to put back what's removed here #429 and give Datopianbot a write access to deploy repo.

## Acceptance criteria

* [x] CD is back so that when I push to master branch it auto creates a PR in deploy repo (and deploys to staging site automatically as before)

## Tasks

* [x] put back removed deploy script (basically revert .travis.yml file)
* [x] figure out credentials for datopianbot user
* [x] give it write access to deploy repo
* [x] test it out

**Comment by anuveyatsu** [comment]
@svetozarstojkovic if you cannot get Datopianbot credentials, you have 2 options:

* trigger "Forgot password" so that it sends recovery email which then you can access (ask somebody eg Ioana if they got the email)
* use your own account to do this instead of datopianbot
